version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: db.meli.com
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - DB_DSN=${DB_DSN}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d meli" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_meli_data:/var/lib/postgresql/data/
  meli:
    image: meli
    container_name: api.meli.com
    env_file:
      - .env
    ports:
      - "8080:8080"
  
networks:
  default:
    name: "meli.com"

volumes:
  pg_meli_data: