// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
  id, site, price, smart_time, name, description, nickname
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, site, price, smart_time, name, description, nickname
`

type CreateItemParams struct {
	ID          int32
	Site        string
	Price       string
	SmartTime   pgtype.Timestamp
	Name        string
	Description string
	Nickname    string
}

// items
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ID,
		arg.Site,
		arg.Price,
		arg.SmartTime,
		arg.Name,
		arg.Description,
		arg.Nickname,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Site,
		&i.Price,
		&i.SmartTime,
		&i.Name,
		&i.Description,
		&i.Nickname,
	)
	return i, err
}
