// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

type Item struct {
	ID          string
	Site        string
	Price       string
	SmartTime   string
	Name        string
	Description string
	Nickname    string
}
